# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tiki < Formula
  desc "Terminal-based kanban/scrum board application"
  homepage "https://github.com/boolean-maybe/tiki"
  version "0.3.2"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/boolean-maybe/tiki/releases/download/v0.3.2/tiki_0.3.2_darwin_amd64.tar.gz"
      sha256 "0dafdc440d60d16ebfb5f5544f0332501e21efaf450aec2327d0ce7945f04798"

      define_method(:install) do
        bin.install "tiki"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/boolean-maybe/tiki/releases/download/v0.3.2/tiki_0.3.2_darwin_arm64.tar.gz"
      sha256 "d6a2aa9ca6e9fbaf4f43da5dd5be601757ba553ab5035b80f7a3e11336ab073a"

      define_method(:install) do
        bin.install "tiki"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/boolean-maybe/tiki/releases/download/v0.3.2/tiki_0.3.2_linux_amd64.tar.gz"
      sha256 "9273cbcd136b283af7883935512d16bda5634c532d95ab9ee2bce2c64ea6de03"
      define_method(:install) do
        bin.install "tiki"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/boolean-maybe/tiki/releases/download/v0.3.2/tiki_0.3.2_linux_arm64.tar.gz"
      sha256 "9f51671c7a656be4cc688f735059f5d852c899ebb1d3f0719973412bbcb05b87"
      define_method(:install) do
        bin.install "tiki"
      end
    end
  end

  test do
    system "#{bin}/tiki --version"
  end
end
