# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tiki < Formula
  desc "Terminal-based kanban/scrum board application"
  homepage "https://github.com/boolean-maybe/tiki"
  version "0.3.4"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/boolean-maybe/tiki/releases/download/v0.3.4/tiki_0.3.4_darwin_amd64.tar.gz"
      sha256 "91f670f5b828c61c5aec1f2f763b1a7e75a2085c61b89977bdff9a467f9a3246"

      define_method(:install) do
        bin.install "tiki"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/boolean-maybe/tiki/releases/download/v0.3.4/tiki_0.3.4_darwin_arm64.tar.gz"
      sha256 "5d10454372615edae472403b3d998632ab390cbdb52107c3d22ff6361c59cc84"

      define_method(:install) do
        bin.install "tiki"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/boolean-maybe/tiki/releases/download/v0.3.4/tiki_0.3.4_linux_amd64.tar.gz"
      sha256 "2b1b107e4d695052a18064a6f3a08547f57ffd0cc7f9b95a90af4be8c27d6401"
      define_method(:install) do
        bin.install "tiki"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/boolean-maybe/tiki/releases/download/v0.3.4/tiki_0.3.4_linux_arm64.tar.gz"
      sha256 "39a4b7ec2e2b4811b97526f84cc7e824a80ab71077449ad533c650c532805b18"
      define_method(:install) do
        bin.install "tiki"
      end
    end
  end

  test do
    system "#{bin}/tiki --version"
  end
end
